### ISSUE TITLE
Question about electron beam parameters

### ISSUE THREAD

**Issue by zhangli28** [BLAST-ImpactX/impactx#580]
Hi @n01r ,

I have a question about retrieving the electron beam parameter information.

**In the plot_chicane.py example, does the following give electron beam transverse size and emittance evolution with propagation distance ?**

here, x & y denotes the transverse direction **(right ?)**
**but what is "t" for ?**

**Is it possible to get the same way twiss parameters of the electron beam ?**

**Comment by n01r** [comment]
Hi @zhangli28,

Yes, `x` and `y` are the transverse directions and `t` denotes the canonical variable for the difference between arrival time of the beam particle and the reference particle. All coordinates in ImpactX are expressed in relation to a beam reference particle. See [Coordinates & Units](https://impactx.readthedocs.io/en/latest/theory/intro.html#coordinates-and-units) for more details.

The reference particle coordinates are written out in `diags/ref_particle.*`.

We also provide diagnostics directly for the Twiss parameters and other beam characteristics: See [Reduced Beam Characteristics](https://impactx.readthedocs.io/en/latest/dataanalysis/dataanalysis.html#reduced-beam-characteristics). :)

**Comment by zhangli28** [comment]
Hi @n01r , thank you so much for prompt reply.

I will check the links you provided and see if I can understand what I am looking for. 
I will come back if I will get confused at any point. 

Thank you.

**Comment by n01r** [comment]
Yea, no worries, sounds good. :)

**Comment by zhangli28** [comment]
Hi @n01r , I have some question about preparing the input electron beam parameters for impactX chicane file. 

I tried to make 2 slides for putting my question. Please, can you see the attached file and say something what I should do.

**Comment by zhangli28** [comment]
Hi @n01r , do you have any suggestion how to give input beam parameters ?

**Comment by n01r** [comment]
Hi @zhangli28, thank you for your slides! If I interpret them correctly then there may be a misunderstanding with the $`\beta`$ and $`\gamma`$.

It is unfortunate that in beam physics $`\beta`$ and $`\gamma`$ are the names for both the relativistic Lorentz parameters as well as the [Courant-Snyder / Twiss parameters](https://en.wikipedia.org/wiki/Courant%E2%80%93Snyder_parameters)

In the [theory section](https://impactx.readthedocs.io/en/latest/theory/intro.html#beam-distribution-input) here we make that distinction in the text. Perhaps we could put a bigger note box there.
If you only have the $`\sigma_x`$, $`\sigma_{p_x}`$, etc. available you can use the relation $`{\displaystyle \epsilon ^{2}=\langle x^{2}\rangle \langle x'^{2}\rangle -\langle xx'\rangle ^{2}}`$ to get the emittance because $`{\sigma_x}^2 = \langle x^2 \rangle`$.

We have two methods for [beam distribution input](https://impactx.readthedocs.io/en/latest/usage/parameters.html#initial-beam-distributions) from analytical parameters at the moment:
- one is via the axis intercepts of the phase space ellipse, which we called $`\lambda`$, where in, e.g., $`\lambda_x = \sqrt{\epsilon_x / \gamma}`$ and the $`\gamma`$ is the Courant-Snyder variable, not the Lorentz parameter.
- the other is via the Courant-Snyder / Twiss parameters themselves

**Comment by zhangli28** [comment]
Hi @n01r , thanks for clearing the confusion. I strongly support or recommend to use the beta_twiss, gamma_twiss for Twiss parameters and normal beta, gamma for relativistic factors. This way is self consistent.

I also strongly request to add (in the documentation) an example input file based on Courant-Snyder / Twiss parameters. This will really help the user.

The Courant-Snyder / Twiss parameters approach looks straight forward, but if you have any example file based on Courant-Snyder / Twiss parameters, can you give me. 

Thank you.

**Comment by n01r** [comment]
We still need to document the `distribution_generation` or `distgen` example, but here is an input file: https://github.com/ECP-WarpX/impactx/blob/development/examples%2Fdistgen%2Finput_kvdist_twiss.in

**Comment by zhangli28** [comment]
Hi @n01r , wow !  thank you for so kind and helpful. Thank you so many times.

**Comment by zhangli28** [comment]
Hi @n01r , one final question

**"T"** still not clear to me, if you help me to understand what alphaT, betaT and emittT are ? And how to find there values.

```ini
# is there any formula to calculate these values

beam.alphaT = 0.0          
beam.betaT = 0.5
beam.emittT = 2e-06
```

**Comment by cemitch99** [comment]
In ImpactX, the parameter T denotes the longitudinal coordinate of a particle within the beam.  For beam output at a monitor location s, T represents the difference in the arrival-time between the particle and the arrival-time of the reference particle.  It is always normalized by (multiplied by) the speed of light c, so that it has units of meters.

The momentum conjugate to T is denoted Pt, and it represents the beam energy (with a minus sign, which is required to make these coordinates canonical).  It is measured relative to the reference particle, and normalized by c*p, where p here is the magnitude of the reference momentum.

For a beam at high energy (in the ultrarelativistic limit), (T,Pt) coincides with (-Z,-delta), where delta is the relative energy deviation.

alphaT, betaT, and emittT are related to (T,Pt) in the same way that alphaX, betaX, and emittX are related to (X,Px).  For example, sigma_T = sqrt(betaT*emittT), etc.

**Comment by zhangli28** [comment]
Dear @n01r @cemitch99 @ax3l thank you so much. I am also looking forward to the extension of input deck as mentioned above by @ax3l .
