### ISSUE TITLE
Parallel Particle Init

### ISSUE THREAD

**Issue by ax3l** [BLAST-ImpactX/impactx#68]
We need to improve the particle initialization: to allow having a first few boxes initially, initialize in parallel & redistribute.

https://github.com/ECP-WarpX/impactx/blob/4b7fa17b1404fb6d21ab38636114befd9722bbf6/src/particles/ImpactXParticleContainer.cpp#L103

Currently, we will be limited to initializing as many particles as a single GPU can handle (even if we run on multiple GPUs).

**Comment by ax3l** [comment]
initially ping-ing @atmyers and @RemiLehe to discuss this in the coming meeting

**Comment by atmyers** [comment]
Getting back to this. Currently, we can't use the `ParticleReduce` functions in AMReX prior to calling Redistribute. The reason is that we always add the particles to grid 0, tile 0 of level 0 to the particle container, whether or not that's a valid destination for a given process. However, it wouldn't be hard to modify the reduction functions AMReX to simply loop over all tiles, whether they are "valid" or not. I think this is maybe the cleanest way to do this, since then we can just call AddNParticles, then the existing "compute min and max particle positions" function in ImpactX, then call Redistribute. What do you think @ax3l ?

**Comment by ax3l** [comment]
Discussed on Slack and implemented in AMReX via https://github.com/AMReX-Codes/amrex/pull/2695 :tada:
